name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: /home/runner/work/Drocsid/code/drocsid/package.json

      - name: Run tests
        run: npm test
