name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: code
        run: npm install

      - name: Run tests
        run: npm test
